name: Webinar Subtitle Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg fonts-ipafont-gothic

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ① Whisperで audio.srt を作る
      - name: Generate English subtitles
        run: |
          python main.py

      # ② 翻訳して audio_ja.srt を作る（★これが今まで無かった）
      - name: Translate subtitles to Japanese
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python translate_srt.py

      # ③ 日本語字幕を焼き込む
      - name: Burn Japanese subtitles
        run: |
          python burn.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: webinar-subtitled-video
          path: webinar_subtitled_test.mp4
